require('./resources/Account.tests');
require('./resources/Bin.tests');
require('./resources/Element.tests');
require('./resources/Entity.tests');
require('./resources/Merchant.tests');
require('./resources/Payment.tests');
require('./resources/Report.tests');
require('./resources/RoutingNumber.tests');
require('./resources/Webhook.tests');
