export const WebhookTypes = {
  payment_create: 'payment.create',
  payment_update: 'payment.update',
  account_create: 'account.create',
  account_update: 'account.update',
  entity_update: 'entity.update',
  entity_create: 'entity.create',
  account_verification_create: 'account_verification.create',
  account_verification_update: 'account_verification.update',
  payment_reversal_create: 'payment_reversal.create',
  payment_reversal_update: 'payment_reversal.update',
  connection_create: 'connection.create',
  connection_update: 'connection.update',
  transaction_create: 'transaction.create',
  transaction_update: 'transaction.update',
  report_create: 'report.create',
  report_update: 'report.update',
  product_create: 'product.create',
  product_update: 'product.update',
  subscription_create: 'subscription.create',
  subscription_update: 'subscription.update',
  credit_score_create: 'credit_score.create',
  credit_score_update: 'credit_score.update',
  payoff_create: 'payoff.create',
  payoff_update: 'payoff.update',
  entity_verification_session_create: 'entity_verification_session.create',
  entity_verification_session_update: 'entity_verification_session.update',
  connect_create: 'connect.create',
  connect_update: 'connect.update',
  connect_available: 'connect.available',
  balance_create: 'balance.create',
  balance_update: 'balance.update',
  identity_create: 'identity.create',
  identity_update: 'identity.update',
  account_verification_session_create: 'account_verification_session.create',
  account_verification_session_update: 'account_verification_session.update',
  card_brand_create: 'card_brand.create',
  card_brand_update: 'card_brand.update',
  card_brand_available: 'card_brand.available',
  sensitive_create: 'sensitive.create',
  sensitive_update: 'sensitive.update',
  update_create: 'update.create',
  update_update: 'update.update',
  attribute_create: 'attribute.create',
  attribute_update: 'attribute.update',
  entity_attribute_create: 'entity_attribute.create',
  entity_attribute_update: 'entity_attribute.update',
  account_attribute_create: 'account_attribute.create',
  account_attribute_update: 'account_attribute.update',
  account_opened: 'account.opened',
  account_closed: 'account.closed',
  credit_score_increased: 'credit_score.increased',
  credit_score_decreased: 'credit_score.decreased',
  entity_attribute_credit_health_open_accounts_value_increased: 'entity_attribute.credit_health_open_accounts_value.increased',
  entity_attribute_credit_health_open_accounts_value_decreased: 'entity_attribute.credit_health_open_accounts_value.decreased',
  entity_attribute_credit_health_total_accounts_value_increased: 'entity_attribute.credit_health_total_accounts_value.increased',
  entity_attribute_credit_health_total_accounts_value_decreased: 'entity_attribute.credit_health_total_accounts_value.decreased',
  entity_attribute_credit_health_credit_card_usage_value_increased: 'entity_attribute.credit_health_credit_card_usage_value.increased',
  entity_attribute_credit_health_credit_card_usage_value_decreased: 'entity_attribute.credit_health_credit_card_usage_value.decreased',
  entity_attribute_credit_health_soft_inquiries_value_increased: 'entity_attribute.credit_health_soft_inquiries_value.increased',
  entity_attribute_credit_health_soft_inquiries_value_decreased: 'entity_attribute.credit_health_soft_inquiries_value.decreased',
  entity_attribute_credit_health_hard_inquiries_value_increased: 'entity_attribute.credit_health_hard_inquiries_value.increased',
  entity_attribute_credit_health_hard_inquiries_value_decreased: 'entity_attribute.credit_health_hard_inquiries_value.decreased',
  entity_attribute_revolving_credit_card_balance_total_increased: 'entity_attribute.revolving_credit_card_balance_total.increased',
  entity_attribute_revolving_credit_card_balance_total_decreased: 'entity_attribute.revolving_credit_card_balance_total.decreased',
  entity_attribute_personal_loan_balance_total_increased: 'entity_attribute.personal_loan_balance_total.increased',
  entity_attribute_personal_loan_balance_total_decreased: 'entity_attribute.personal_loan_balance_total.decreased',
  entity_attribute_revolving_credit_card_balance_change_30d_increased: 'entity_attribute.revolving_credit_card_balance_change_30d.increased',
  entity_attribute_revolving_credit_card_balance_change_30d_decreased: 'entity_attribute.revolving_credit_card_balance_change_30d.decreased',
  entity_attribute_revolving_credit_card_balance_change_60d_increased: 'entity_attribute.revolving_credit_card_balance_change_60d.increased',
  entity_attribute_revolving_credit_card_balance_change_60d_decreased: 'entity_attribute.revolving_credit_card_balance_change_60d.decreased',
  entity_attribute_revolving_credit_card_balance_change_90d_increased: 'entity_attribute.revolving_credit_card_balance_change_90d.increased',
  entity_attribute_revolving_credit_card_balance_change_90d_decreased: 'entity_attribute.revolving_credit_card_balance_change_90d.decreased',
  entity_attribute_personal_loan_balance_change_30d_increased: 'entity_attribute.personal_loan_balance_change_30d.increased',
  entity_attribute_personal_loan_balance_change_30d_decreased: 'entity_attribute.personal_loan_balance_change_30d.decreased',
  entity_attribute_personal_loan_balance_change_60d_increased: 'entity_attribute.personal_loan_balance_change_60d.increased',
  entity_attribute_personal_loan_balance_change_60d_decreased: 'entity_attribute.personal_loan_balance_change_60d.decreased',
  entity_attribute_personal_loan_balance_change_90d_increased: 'entity_attribute.personal_loan_balance_change_90d.increased',
  entity_attribute_personal_loan_balance_change_90d_decreased: 'entity_attribute.personal_loan_balance_change_90d.decreased',
  entity_attribute_usage_pattern_changed: 'entity_attribute.usage_pattern.changed',
  entity_attribute_delinquency_flag_credit_cards_set: 'entity_attribute.delinquency_flag_credit_cards.set',
  entity_attribute_delinquency_flag_credit_cards_cleared: 'entity_attribute.delinquency_flag_credit_cards.cleared',
  entity_attribute_weighted_average_apr_credit_card_increased: 'entity_attribute.weighted_average_apr_credit_card.increased',
  entity_attribute_weighted_average_apr_credit_card_decreased: 'entity_attribute.weighted_average_apr_credit_card.decreased',
  entity_attribute_weighted_average_apr_personal_loan_increased: 'entity_attribute.weighted_average_apr_personal_loan.increased',
  entity_attribute_weighted_average_apr_personal_loan_decreased: 'entity_attribute.weighted_average_apr_personal_loan.decreased',
  entity_attribute_credit_card_utilization_increased: 'entity_attribute.credit_card_utilization.increased',
  entity_attribute_credit_card_utilization_decreased: 'entity_attribute.credit_card_utilization.decreased',
  entity_attribute_personal_loan_utilization_increased: 'entity_attribute.personal_loan_utilization.increased',
  entity_attribute_personal_loan_utilization_decreased: 'entity_attribute.personal_loan_utilization.decreased',
  entity_attribute_overall_utilization_increased: 'entity_attribute.overall_utilization.increased',
  entity_attribute_overall_utilization_decreased: 'entity_attribute.overall_utilization.decreased',
  entity_attribute_revolving_credit_card_utilization_trend_30d_increased: 'entity_attribute.revolving_credit_card_utilization_trend_30d.increased',
  entity_attribute_revolving_credit_card_utilization_trend_30d_decreased: 'entity_attribute.revolving_credit_card_utilization_trend_30d.decreased',
  entity_attribute_personal_loan_utilization_trend_30d_increased: 'entity_attribute.personal_loan_utilization_trend_30d.increased',
  entity_attribute_personal_loan_utilization_trend_30d_decreased: 'entity_attribute.personal_loan_utilization_trend_30d.decreased',
  entity_attribute_credit_limit_total_increased: 'entity_attribute.credit_limit_total.increased',
  entity_attribute_credit_limit_total_decreased: 'entity_attribute.credit_limit_total.decreased',
  entity_attribute_personal_loan_amount_total_increased: 'entity_attribute.personal_loan_amount_total.increased',
  entity_attribute_personal_loan_amount_total_decreased: 'entity_attribute.personal_loan_amount_total.decreased',
  entity_attribute_mortgage_loan_amount_total_increased: 'entity_attribute.mortgage_loan_amount_total.increased',
  entity_attribute_mortgage_loan_amount_total_decreased: 'entity_attribute.mortgage_loan_amount_total.decreased',
  entity_attribute_overall_loan_amount_total_increased: 'entity_attribute.overall_loan_amount_total.increased',
  entity_attribute_overall_loan_amount_total_decreased: 'entity_attribute.overall_loan_amount_total.decreased',
  entity_attribute_personal_loan_monthly_installments_estimate_increased: 'entity_attribute.personal_loan_monthly_installments_estimate.increased',
  entity_attribute_personal_loan_monthly_installments_estimate_decreased: 'entity_attribute.personal_loan_monthly_installments_estimate.decreased',
  entity_attribute_next_payment_minimum_total_credit_cards_increased: 'entity_attribute.next_payment_minimum_total_credit_cards.increased',
  entity_attribute_next_payment_minimum_total_credit_cards_decreased: 'entity_attribute.next_payment_minimum_total_credit_cards.decreased',
  entity_attribute_payment_to_minimum_ratio_avg_credit_cards_increased: 'entity_attribute.payment_to_minimum_ratio_avg_credit_cards.increased',
  entity_attribute_payment_to_minimum_ratio_avg_credit_cards_decreased: 'entity_attribute.payment_to_minimum_ratio_avg_credit_cards.decreased',
  entity_attribute_revolving_credit_card_utilization_trend_90d_increased: 'entity_attribute.revolving_credit_card_utilization_trend_90d.increased',
  entity_attribute_revolving_credit_card_utilization_trend_90d_decreased: 'entity_attribute.revolving_credit_card_utilization_trend_90d.decreased',
  entity_attribute_revolving_credit_card_utilization_delta_30d_increased: 'entity_attribute.revolving_credit_card_utilization_delta_30d.increased',
  entity_attribute_revolving_credit_card_utilization_delta_30d_decreased: 'entity_attribute.revolving_credit_card_utilization_delta_30d.decreased',
  entity_attribute_revolving_credit_card_utilization_delta_60d_increased: 'entity_attribute.revolving_credit_card_utilization_delta_60d.increased',
  entity_attribute_revolving_credit_card_utilization_delta_60d_decreased: 'entity_attribute.revolving_credit_card_utilization_delta_60d.decreased',
  entity_attribute_revolving_credit_card_utilization_delta_90d_increased: 'entity_attribute.revolving_credit_card_utilization_delta_90d.increased',
  entity_attribute_revolving_credit_card_utilization_delta_90d_decreased: 'entity_attribute.revolving_credit_card_utilization_delta_90d.decreased',
  entity_attribute_personal_loan_utilization_trend_90d_increased: 'entity_attribute.personal_loan_utilization_trend_90d.increased',
  entity_attribute_personal_loan_utilization_trend_90d_decreased: 'entity_attribute.personal_loan_utilization_trend_90d.decreased',
  entity_attribute_personal_loan_utilization_delta_30d_increased: 'entity_attribute.personal_loan_utilization_delta_30d.increased',
  entity_attribute_personal_loan_utilization_delta_30d_decreased: 'entity_attribute.personal_loan_utilization_delta_30d.decreased',
  entity_attribute_personal_loan_utilization_delta_60d_increased: 'entity_attribute.personal_loan_utilization_delta_60d.increased',
  entity_attribute_personal_loan_utilization_delta_60d_decreased: 'entity_attribute.personal_loan_utilization_delta_60d.decreased',
  entity_attribute_personal_loan_utilization_delta_90d_increased: 'entity_attribute.personal_loan_utilization_delta_90d.increased',
  entity_attribute_personal_loan_utilization_delta_90d_decreased: 'entity_attribute.personal_loan_utilization_delta_90d.decreased',
  entity_attribute_mortgage_balance_total_increased: 'entity_attribute.mortgage_balance_total.increased',
  entity_attribute_mortgage_balance_total_decreased: 'entity_attribute.mortgage_balance_total.decreased',
  entity_attribute_mortgage_balance_change_30d_increased: 'entity_attribute.mortgage_balance_change_30d.increased',
  entity_attribute_mortgage_balance_change_30d_decreased: 'entity_attribute.mortgage_balance_change_30d.decreased',
  entity_attribute_mortgage_balance_change_60d_increased: 'entity_attribute.mortgage_balance_change_60d.increased',
  entity_attribute_mortgage_balance_change_60d_decreased: 'entity_attribute.mortgage_balance_change_60d.decreased',
  entity_attribute_mortgage_balance_change_90d_increased: 'entity_attribute.mortgage_balance_change_90d.increased',
  entity_attribute_mortgage_balance_change_90d_decreased: 'entity_attribute.mortgage_balance_change_90d.decreased',
  entity_attribute_weighted_average_apr_mortgage_increased: 'entity_attribute.weighted_average_apr_mortgage.increased',
  entity_attribute_weighted_average_apr_mortgage_decreased: 'entity_attribute.weighted_average_apr_mortgage.decreased',
  entity_attribute_mortgage_utilization_trend_30d_increased: 'entity_attribute.mortgage_utilization_trend_30d.increased',
  entity_attribute_mortgage_utilization_trend_30d_decreased: 'entity_attribute.mortgage_utilization_trend_30d.decreased',
  entity_attribute_mortgage_utilization_trend_90d_increased: 'entity_attribute.mortgage_utilization_trend_90d.increased',
  entity_attribute_mortgage_utilization_trend_90d_decreased: 'entity_attribute.mortgage_utilization_trend_90d.decreased',
  entity_attribute_mortgage_utilization_delta_30d_increased: 'entity_attribute.mortgage_utilization_delta_30d.increased',
  entity_attribute_mortgage_utilization_delta_30d_decreased: 'entity_attribute.mortgage_utilization_delta_30d.decreased',
  entity_attribute_mortgage_utilization_delta_60d_increased: 'entity_attribute.mortgage_utilization_delta_60d.increased',
  entity_attribute_mortgage_utilization_delta_60d_decreased: 'entity_attribute.mortgage_utilization_delta_60d.decreased',
  entity_attribute_mortgage_utilization_delta_90d_increased: 'entity_attribute.mortgage_utilization_delta_90d.increased',
  entity_attribute_mortgage_utilization_delta_90d_decreased: 'entity_attribute.mortgage_utilization_delta_90d.decreased',
  entity_attribute_installment_balance_total_increased: 'entity_attribute.installment_balance_total.increased',
  entity_attribute_installment_balance_total_decreased: 'entity_attribute.installment_balance_total.decreased',
  entity_attribute_installment_balance_change_30d_increased: 'entity_attribute.installment_balance_change_30d.increased',
  entity_attribute_installment_balance_change_30d_decreased: 'entity_attribute.installment_balance_change_30d.decreased',
  entity_attribute_installment_balance_change_60d_increased: 'entity_attribute.installment_balance_change_60d.increased',
  entity_attribute_installment_balance_change_60d_decreased: 'entity_attribute.installment_balance_change_60d.decreased',
  entity_attribute_installment_balance_change_90d_increased: 'entity_attribute.installment_balance_change_90d.increased',
  entity_attribute_installment_balance_change_90d_decreased: 'entity_attribute.installment_balance_change_90d.decreased',
  entity_attribute_overall_utilization_trend_30d_increased: 'entity_attribute.overall_utilization_trend_30d.increased',
  entity_attribute_overall_utilization_trend_30d_decreased: 'entity_attribute.overall_utilization_trend_30d.decreased',
  entity_attribute_overall_utilization_trend_90d_increased: 'entity_attribute.overall_utilization_trend_90d.increased',
  entity_attribute_overall_utilization_trend_90d_decreased: 'entity_attribute.overall_utilization_trend_90d.decreased',
  entity_attribute_overall_utilization_delta_30d_increased: 'entity_attribute.overall_utilization_delta_30d.increased',
  entity_attribute_overall_utilization_delta_30d_decreased: 'entity_attribute.overall_utilization_delta_30d.decreased',
  entity_attribute_overall_utilization_delta_60d_increased: 'entity_attribute.overall_utilization_delta_60d.increased',
  entity_attribute_overall_utilization_delta_60d_decreased: 'entity_attribute.overall_utilization_delta_60d.decreased',
  entity_attribute_overall_utilization_delta_90d_increased: 'entity_attribute.overall_utilization_delta_90d.increased',
  entity_attribute_overall_utilization_delta_90d_decreased: 'entity_attribute.overall_utilization_delta_90d.decreased',
  entity_attribute_other_balance_total_increased: 'entity_attribute.other_balance_total.increased',
  entity_attribute_other_balance_total_decreased: 'entity_attribute.other_balance_total.decreased',
  entity_attribute_other_balance_change_30d_increased: 'entity_attribute.other_balance_change_30d.increased',
  entity_attribute_other_balance_change_30d_decreased: 'entity_attribute.other_balance_change_30d.decreased',
  entity_attribute_other_balance_change_60d_increased: 'entity_attribute.other_balance_change_60d.increased',
  entity_attribute_other_balance_change_60d_decreased: 'entity_attribute.other_balance_change_60d.decreased',
  entity_attribute_other_balance_change_90d_increased: 'entity_attribute.other_balance_change_90d.increased',
  entity_attribute_other_balance_change_90d_decreased: 'entity_attribute.other_balance_change_90d.decreased',
  manual_connect_create: 'manual_connect.create',
  manual_connect_update: 'manual_connect.update',
  payment_instrument_create: 'payment_instrument.create',
  payment_instrument_update: 'payment_instrument.update',
  method_jwk_create: 'method_jwk.create',
  method_jwk_update: 'method_jwk.update',
  credit_score_available: 'credit_score.available',
  account_number_update: 'account.number.update',
  account_balance_increased: 'account.balance_increased',
  account_balance_decreased: 'account.balance_decreased',
  account_credit_limit_increased: 'account.credit_limit_increased',
  account_credit_limit_decreased: 'account.credit_limit_decreased',
  entity_new_accounts_pending_consent: 'entity.new_accounts_pending_consent',
  entity_vehicle_create: 'entity_vehicle.create',
  entity_vehicle_update: 'entity_vehicle.update',
} as const;

export type TWebhookTypes = typeof WebhookTypes[keyof typeof WebhookTypes];

export const WebhookStatus = {
  active: 'active',
  disabled: 'disabled',
  deleted: 'deleted',
  requires_attention: 'requires_attention',
} as const;

export type TWebhookStatus = typeof WebhookStatus[keyof typeof WebhookStatus];

export type TUpdateWebhookStatus = 'active' | 'disabled';

export interface IWebhook {
  id: string;
  type: TWebhookTypes;
  url: string;
  metadata: {} | null;
  created_at: string;
  updated_at: string;
  expand_event: boolean;
  error: object | null;
  status: TWebhookStatus | null;
};

export interface IWebhookCreateOpts {
  type: TWebhookTypes;
  url: string;
  auth_token?: string;
  hmac_secret?: string;
  metadata?: {};
  expand_event?: boolean;
};

export interface IWebhookUpdateOpts {
  status: TUpdateWebhookStatus;
};