# This is a basic workflow to help you get started with Actions

name: Mocha tests

# Controls when the action will run.
on:
  push:
    branches-ignore:
      - 'master'
      - 'release'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mocha-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install doppler
        run: |
          (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sudo sh
      - name: Install NPM packages
        run: |
          npm install
      - name: Excute mocha tests
        run: |
          doppler run -t ${{ secrets.TEST_DOPPLER_TOKEN }} npm run test
